0.1.8
* more file protections
l* ast-modification date comparison for files with same basename, but different hashes

diff --git a/merge b/merge
--- a/merge
+++ b/merge
@@ -1,7 +1,7 @@
 #!/bin/zsh
 # shellcheck shell=bash
 
-# merge v0.1.7
+# merge v0.1.8
 
 export PATH=/usr/bin:/bin:/usr/sbin:/sbin
 export SYSTEM_VERSION_COMPAT=0
@@ -96,6 +96,73 @@ $HOMEDIR/Library
 EOF
 # plus: $HOMEDIR
 
+read -d '' userblocked_root <<EOF
+$HOMEDIR/.bash_history
+$HOMEDIR/.bash_profile
+$HOMEDIR/.bash_sessions
+$HOMEDIR/.cache
+$HOMEDIR/.cargo
+$HOMEDIR/.config
+$HOMEDIR/.cups
+$HOMEDIR/.docker
+$HOMEDIR/.dropbox
+$HOMEDIR/.gem
+$HOMEDIR/.gitconfig
+$HOMEDIR/.gnupg
+$HOMEDIR/.gnupg_pre_2.1
+$HOMEDIR/.ipfs
+$HOMEIDR/.iterm2
+$HOMEDIR/.iterm2_shell_integration.bash
+$HOMEDIR/.iterm2_shell_integration.zsh
+$HOMEDIR/.local
+$HOMEDIR/.oracle_jre_usage
+$HOMEDIR/.profile
+$HOMEDIR/.python_history
+$HOMEDIR/.sh_history
+$HOMEDIR/.sqlite_history
+$HOMEDIR/ssh
+$HOMEDIR/.Trash
+$HOMEDIR/.vim
+$HOMEDIR/.viminfo
+$HOMEDIR/.zcompdump
+$HOMEDIR/.zhistory
+$HOMEDIR/.zlogin
+$HOMEDIR/.zlogout
+$HOMEDIR/.zprezto
+$HOMEDIR/.zpreztorc
+$HOMEDIR/.zprofile
+$HOMEDIR/.zsh_history
+$HOMEDIR/.zshenv
+$HOMEDIR/.zshrc
+$HOMEDIR/Applications
+$HOMEDIR/bin
+$HOMEDIR/Desktop
+$HOMEDIR/Developer
+$HOMEDIR/Documents
+$HOMEDIR/Downloads
+$HOMEDIR/Library
+$HOMEDIR/Movies
+$HOMEDIR/Music
+$HOMEDIR/Pictures
+$HOMEDIR/Public
+$HOMEDIR/Sites
+EOF
+
+read -d '' userblocked_other <<EOF
+$HOMEDIR/Developer/Applications
+$HOMEDIR/Library/Developer
+$HOMEDIR/Movies/iMovie Library.imovielibrary
+$HOMEDIR/Movies/iMovie Theater.theater
+$HOMEDIR/Movies/TV
+$HOMEDIR/Movies/TV/TV Library.tvlibrary
+$HOMEDIR/Music/iTunes
+$HOMEDIR/Music/Music
+$HOMEDIR/Music/Music/Music Library.musiclibrary
+$HOMEDIR/Photos/Photo Booth Library
+$HOMEDIR/Photos/Photos Library.photoslibrary
+$HOMEDIR/Public/Drop Box
+EOF
+
 if [[ $1 == "-d" ]] || [[ $1 == "--down" ]] ; then
 	mergedown=true
 	shift
@@ -127,24 +194,30 @@ if [[ $# -eq 1 ]] ; then
 		else
 			parentdir=$(dirname "$filepath")
 			if [[ $parentdir == "$HOMEDIR" ]] ; then
-				echo "Error: protected home file!" >&2
-				exit 1
+				if echo "$userblocked_root" | grep -q "^$filepath$" &>/dev/null ; then
+					echo "Error - protected home file: $filepath" >&2
+					exit 1
+				fi
 			elif [[ $parentdir == "/" ]] ; then
-				echo "Error: protected root file" >&2
+				echo "Error - protected root file: $filepath" >&2
 				exit 1
 			else
 				if echo "$userparents" | grep -q "^$parentdir$" &>/dev/null ; then
-					echo "Error: protected user file!" >&2
+					echo "Error - protected user file: $filepath" >&2
 					exit 1
 				else
 					if echo "$sysparents" | grep -q "$parentdir$" &>/dev/null ; then
-						echo "Error: protected system file!" >&2
+						echo "Error - protected system file: $filepath" >&2
 						exit 1
 					fi
 				fi
+				if echo "$userblocked_other" | grep -q "^$filepath$" &>/dev/null ; then
+					echo "Error - protected user file: $filepath" >&2
+					exit 1
+				fi
 			fi
 			if ! [[ -w "$filepath" ]] ; then
-				echo "Error: directory not writable!" >&2
+				echo "Error - directory not writable: $filepath" >&2
 				exit 1
 			fi
 			allregular=false
@@ -159,6 +232,15 @@ if [[ $# -eq 1 ]] ; then
 						while read -r quicklistfile
 						do
 							sourcebase=$(basename "$quicklistfile")
+							if [[ $sourcebase == ".DS_Store" ]] ; then
+								if rm -f "$quicklistfile" &>/dev/null ; then
+									echo "Removed: $quicklistfile"
+									fdeleted=true
+									continue
+								else
+									echo "rm error: $quicklistfile"
+								fi
+							fi
 							if echo "$deletions" | grep -q "^$sourcebase$" &>/dev/null ; then
 								if rm -f "$quicklistfile" &>/dev/null ; then
 									echo "Removed: $quicklistfile"
@@ -208,21 +290,28 @@ else
 	for filepath in "$@"
 	do
 		parentdir=$(dirname "$filepath")
+		filename=$(basename "$filepath")
 		if [[ $parentdir == "$HOMEDIR" ]] ; then
-			echo "Error: protected home file!" >&2
-			exit 1
+			if echo "$userblocked_root" | grep -q "^$filepath$" &>/dev/null ; then
+				echo "Error - protected home file: $filepath" >&2
+				exit 1
+			fi
 		elif [[ $parentdir == "/" ]] ; then
-			echo "Error: protected root file" >&2
+			echo "Error - protected root file: $filepath" >&2
 			exit 1
 		else
 			if echo "$userparents" | grep -q "^$parentdir$" &>/dev/null ; then
-				echo "Error: protected user file!" >&2
+				echo "Error - protected user file: $filepath" >&2
 				exit 1
 			else
 				if echo "$sysparents" | grep -q "$parentdir$" &>/dev/null ; then
-					echo "Error: protected system file!" >&2
+					echo "Error - protected system file: $filepath" >&2
 					exit 1
 				fi
+			fi
+			if echo "$userblocked_other" | grep -q "^$filepath$" &>/dev/null ; then
+				echo "Error - protected user file: $filepath" >&2
+				exit 1
 			fi
 		fi
 		if ! [[ -w "$filepath" ]] ; then
@@ -278,6 +367,8 @@ else
 	fi
 fi
 
+exit ###
+
 currentposix=$(date +%s)
 if [[ $(basename "$targetdir") == "merged folder" ]] && [[ -d "$targetdir" ]] ; then
 	targetdir="$targetdir $currentposix"
@@ -329,13 +420,23 @@ if $mergedown ; then
 	while read -r sourcefile
 	do
 		sourcebase=$(basename "$sourcefile")
+		if [[ $sourcebase == ".DS_Store" ]] ; then
+			if rm -f "$sourcefile" &>/dev/null ; then
+				echo "Removed: $sourcefile"
+			else
+				echo "rm error: $sourcefile" >&2
+			fi
+			continue
+		fi
 		sourceparent=$(dirname "$sourcefile")
 		if $rmfiles ; then
 			if echo "$deletions" | grep -q "^$sourcebase$" &>/dev/null ; then
 				if rm -f "$sourcefile" &>/dev/null ; then
 					echo "Removed: $sourcefile"
-					continue
+				else
+					echo "rm error: $sourcefile" >&2
 				fi
+				continue
 			fi
 			if $checkext ; then
 				suffix="${sourcebase##*.}"
@@ -343,9 +444,11 @@ if $mergedown ; then
 				if [[ $extension ]] ; then
 					if echo "$suffixes" | grep -q "^\*\.$extension$" &>/dev/null ; then
 						if rm -f "$sourcefile" &>/dev/null ; then
-							echo "Removed: $sourcefile"
-							continue
+							echo "Removed (*.$extension): $sourcefile"
+						else
+							echo "rm error (*.$extension): $sourcefile" >&2
 						fi
+						continue
 					fi
 				fi
 			fi
@@ -374,24 +477,72 @@ if $mergedown ; then
 				sourcehash=$(crc32 "$sourcefile")
 				targethash=$(crc32 "$targetdir/$sourcebase")
 				if [[ $sourcehash != "$targethash" ]] ; then
-					mkdir "$targetdir/$sourcebase $sourcehash" 2>/dev/null
-					if ! mv -f "$sourcefile" "$targetdir/$sourcebase $sourcehash/$sourcebase" &>/dev/null ; then
-						volsource=$(df "$sourcefile" | tail -1 | awk '{print $NF}')
-						voltarget=$(df "$targetdir" | tail -1 | awk '{print $NF}')
-						if [[ $volsource == "$voltarget" ]] ; then
-							echo "mv error: $sourcefile" >&2
-							mverror=true
-						else
-							echo "mv error & different volume - trying to copy instead: $sourcefile"
-							if ! cp -f "$sourcefile" "$targetdir/$sourcebase" &>/dev/null ; then
-								echo "cp error: $sourcefile" >&2
+					sourcedate=$(date -r "$sourcefile" +%s)
+					targetdate=$(date -r "$targetdir/$sourcebase" +%s)
+					if [[ $sourcedate -le $targetdate ]] ; then
+						mkdir "$targetdir/$sourcebase $sourcehash" 2>/dev/null
+						if ! mv -f "$sourcefile" "$targetdir/$sourcebase $sourcehash/$sourcebase" &>/dev/null ; then
+							volsource=$(df "$sourcefile" | tail -1 | awk '{print $NF}')
+							voltarget=$(df "$targetdir" | tail -1 | awk '{print $NF}')
+							if [[ $volsource == "$voltarget" ]] ; then
+								echo "mv error: $sourcefile" >&2
 								mverror=true
 							else
-								echo "File with duplicate basename merged (cp): $sourcefile"
+								echo "mv error & different volume - trying to copy instead: $sourcefile"
+								if ! cp -f "$sourcefile" "$targetdir/$sourcebase $sourcehash/$sourcebase" &>/dev/null ; then
+									echo "cp error: $sourcefile" >&2
+									mverror=true
+								else
+									echo "File with duplicate basename merged (cp): $sourcefile"
+								fi
+							fi
+						else
+							echo "File with duplicate basename merged (mv): $sourcefile"
+						fi
+					elif [[ $sourcedate -gt $targetdate ]] ; then
+						mkdir "$targetdir/$sourcebase $targethash" 2>/dev/null
+						if ! mv -f "$targetdir/$sourcebase" "$targetdir/$sourcebase $targethash/$sourcebase" &>/dev/null ; then
+							echo "mv to subfolder error: $targethash/$sourcebase"
+							mv "$targetdir/$sourcebase $targethash" "$targetdir/$sourcebase $sourcehash" 2>/dev/null
+							if ! mv -f "$sourcefile" "$targetdir/$sourcebase $sourcehash/$sourcebase" &>/dev/null ; then
+								volsource=$(df "$sourcefile" | tail -1 | awk '{print $NF}')
+								voltarget=$(df "$targetdir" | tail -1 | awk '{print $NF}')
+								if [[ $volsource == "$voltarget" ]] ; then
+									echo "mv error: $sourcefile" >&2
+									mverror=true
+								else
+									echo "mv error & different volume - trying to copy instead: $sourcefile"
+									if ! cp -f "$sourcefile" "$targetdir/$sourcebase $sourcehash/$sourcebase" &>/dev/null ; then
+										echo "cp error: $sourcefile" >&2
+										mverror=true
+									else
+										echo "File with duplicate basename merged (cp): $sourcefile"
+									fi
+								fi
+							else
+								echo "File with duplicate basename merged (mv): $sourcefile"
+							fi
+						else
+							echo "Older file moved to subfolder: $targethash/$sourcebase"
+							if ! mv -f "$sourcefile" "$targetdir/$sourcebase" &>/dev/null ; then
+								volsource=$(df "$sourcefile" | tail -1 | awk '{print $NF}')
+								voltarget=$(df "$targetdir" | tail -1 | awk '{print $NF}')
+								if [[ $volsource == "$voltarget" ]] ; then
+									echo "mv error: $sourcefile" >&2
+									mverror=true
+								else
+									echo "mv error & different volume - trying to copy instead: $sourcefile"
+									if ! cp -f "$sourcefile" "$targetdir/$sourcebase" &>/dev/null ; then
+										echo "cp error: $sourcefile" >&2
+										mverror=true
+									else
+										echo "File with duplicate basename merged (cp): $sourcefile"
+									fi
+								fi
+							else
+								echo "File with duplicate basename merged (mv): $sourcefile"
 							fi
 						fi
-					else
-						echo "File with duplicate basename merged (mv): $sourcefile"
 					fi
 				else
 					if ! rm -f "$sourcefile" &>/dev/null ; then
