0.1.5
verbosity + logging

diff --git a/merge b/merge
--- a/merge
+++ b/merge
@@ -1,7 +1,7 @@
 #!/bin/zsh
 # shellcheck shell=bash
 
-# merge v0.1.5
+# merge v0.1.6
 
 export PATH=/usr/bin:/bin:/usr/sbin:/sbin
 export SYSTEM_VERSION_COMPAT=0
@@ -9,6 +9,15 @@ export LANG=en_US.UTF-8
 
 accountname=$(scutil <<< "show State:/Users/ConsoleUser" | awk '/Name :/ && ! /loginwindow/ { print $3 }')
 HOMEDIR=$(eval echo "~$accountname")
+
+logloc="/tmp/local.lcars.merge.log"
+currentdate=$(date)
+if ! [[ -f $logloc ]] ; then
+	echo "++++++++ $currentdate ++++++++" > "$logloc"
+else
+	echo -e "\n++++++++ $currentdate ++++++++" >> "$logloc"
+fi
+exec > >(tee "$logloc") 2>&1
 
 configdir="$HOMEDIR/.config/local.lcars.merge"
 deleteloc="$configdir/deletions"
@@ -45,7 +54,7 @@ fi
 
 if [[ $# -eq 1 ]] ; then
 	if ! [[ -d $* ]] ; then
-		echo "merge will not work with single non-directory files!" >&2
+		echo "Error: no merge of single non-directory files!" >&2
 		exit 1
 	else
 		if ! $mergedown ; then
@@ -72,8 +81,11 @@ if [[ $# -eq 1 ]] ; then
 							sourcebase=$(basename "$quicklistfile")
 							if echo "$deletions" | grep -q "^$sourcebase$" &>/dev/null ; then
 								if rm -f "$quicklistfile" &>/dev/null ; then
+									echo "Removed: $quicklistfile"
 									fdeleted=true
 									continue
+								else
+									echo "rm error: $quicklistfile"
 								fi
 							fi
 							if $checkext ; then
@@ -82,8 +94,11 @@ if [[ $# -eq 1 ]] ; then
 								if [[ $extension ]] ; then
 									if echo "$suffixes" | grep -q "^\*\.$extension$" &>/dev/null ; then
 										if rm -f "$quicklistfile" &>/dev/null ; then
+											echo "Removed (*.$extension): $quicklistfile"
 											fdeleted=true
 											continue
+										else
+											echo "rm error (*.$extension): $quicklistfile"
 										fi
 									fi
 								fi
@@ -113,12 +128,15 @@ else
 	for filepath in "$@"
 	do
 		if ! [[ -w "$filepath" ]] ; then
-			echo "Error: at least one file not writable!" >&2
+			echo "Error: at least one file not writable: $filepath" >&2
 			exit 1
 		fi
 		if [[ -d "$filepath" ]] ; then
 			((dircount++))
 			targetdir="$filepath"
+			echo "Source directory: $filepath"
+		else
+			echo "Source file: $filepath"
 		fi
 		masterparent=$(dirname "$filepath")
 		if [[ $parentlist ]] ; then
@@ -167,13 +185,15 @@ if [[ $(basename "$targetdir") == "merged folder" ]] && [[ -d "$targetdir" ]] ; 
 	targetdir="$targetdir $currentposix"
 fi
 
+echo "Target directory: $targetdir"
+
 if $mergedown ; then
 	if $single ; then
 		allfiles=$(find "$filepath" -mindepth 1 -type f 2>/dev/null | sort)
 		while read -r sourcefile
 		do
 			if ! [[ -w "$sourcefile" ]] ; then
-				echo "Error: at least one file is not writable!" >&2
+				echo "Error: at least one file is not writable: $sourcefile" >&2
 				exit 1
 			fi
 		done < <(echo "$allfiles")
@@ -196,7 +216,7 @@ if $mergedown ; then
 		while read -r sourcefile
 		do
 			if ! [[ -w "$sourcefile" ]] ; then
-				echo "Error: at least one file is not writable!" >&2
+				echo "Error: at least one file is not writable: $sourcefile" >&2
 				exit 1
 			fi
 		done < <(echo "$allfiles")
@@ -214,14 +234,20 @@ if $mergedown ; then
 		sourceparent=$(dirname "$sourcefile")
 		if $rmfiles ; then
 			if echo "$deletions" | grep -q "^$sourcebase$" &>/dev/null ; then
-				rm -f "$sourcefile" &>/dev/null && continue
+				if rm -f "$sourcefile" &>/dev/null ; then
+					echo "Removed: $sourcefile"
+					continue
+				fi
 			fi
 			if $checkext ; then
 				suffix="${sourcebase##*.}"
 				extension=$(echo "$suffix" | tr '[:upper:]' '[:lower:]')
 				if [[ $extension ]] ; then
 					if echo "$suffixes" | grep -q "^\*\.$extension$" &>/dev/null ; then
-						rm -f "$sourcefile" &>/dev/null && continue
+						if rm -f "$sourcefile" &>/dev/null ; then
+							echo "Removed: $sourcefile"
+							continue
+						fi
 					fi
 				fi
 			fi
@@ -239,8 +265,12 @@ if $mergedown ; then
 						if ! cp -f "$sourcefile" "$targetdir/$sourcebase" &>/dev/null ; then
 							echo "cp error: $sourcefile" >&2
 							mverror=true
+						else
+							echo "File merged (cp): $sourcefile"
 						fi
 					fi
+				else
+					echo "File merged (mv): $sourcefile"
 				fi
 			else
 				sourcehash=$(crc32 "$sourcefile")
@@ -258,13 +288,19 @@ if $mergedown ; then
 							if ! cp -f "$sourcefile" "$targetdir/$sourcebase" &>/dev/null ; then
 								echo "cp error: $sourcefile" >&2
 								mverror=true
+							else
+								echo "File with duplicate basename merged (cp): $sourcefile"
 							fi
 						fi
+					else
+						echo "File with duplicate basename merged (mv): $sourcefile"
 					fi
 				else
 					if ! rm -f "$sourcefile" &>/dev/null ; then
 						echo "rm error: could not delete duplicate: $sourcefile"
 						mverror=true
+					else
+						echo "Removed duplicate: $sourcefile"
 					fi
 				fi
 			fi				
@@ -286,7 +322,9 @@ if $mergedown ; then
 						fi
 						if [[ -e "$filepath" ]] ; then
 							if ! mv -f "$filepath" "$trashloc" &>/dev/null ; then
-								echo "Error moving source to trash: $filepath"
+								echo "Error moving source to trash: $filepath" >&2
+							else
+								echo "Moved to trash: $filepath"
 							fi
 						fi
 					else
@@ -304,6 +342,7 @@ if $mergedown ; then
 	fi
 	dirlist=$(find "$targetdir" -mindepth 1 -maxdepth 1 -type d 2>/dev/null)
 	if [[ $dirlist ]] ; then
+		echo "Trying to clean up..."
 		while read -r finaldir
 		do
 			finalfiles=$(find "$finaldir" -mindepth 1 -type f -print -quit 2>/dev/null)
@@ -313,14 +352,22 @@ if $mergedown ; then
 					if [[ $volfinal == "$voltrash" ]] ; then
 						! [[ -d "$HOMEDIR/.Trash/folders $currentposix" ]] && mkdir "$HOMEDIR/.Trash/folders $currentposix" 2>/dev/null
 						finaldirbase=$(basename "$finaldir")
-						mv -f "$finaldir" "$HOMEDIR/.Trash/folders $currentposix/$finaldirbase" 2>/dev/null
+						if mv -f "$finaldir" "$HOMEDIR/.Trash/folders $currentposix/$finaldirbase" &>/dev/null ; then
+							echo "Moved to trash: $finaldir"
+						else
+							echo "Error moving to trash: $finaldir" >&2
+						fi
 					else
 						echo "Different volume - not moving to trash: $finaldir" >&2
 					fi
 				else
 					! [[ -d "$HOMEDIR/.Trash/folders $currentposix" ]] && mkdir "$HOMEDIR/.Trash/folders $currentposix" 2>/dev/null
 					finaldirbase=$(basename "$finaldir")
-					mv -f "$finaldir" "$HOMEDIR/.Trash/folders $currentposix/$finaldirbase" 2>/dev/null
+					if mv -f "$finaldir" "$HOMEDIR/.Trash/folders $currentposix/$finaldirbase" &>/dev/null ; then
+						echo "Moved to trash: $finaldir"
+					else
+						echo "Error moving to trash: $finaldir" >&2
+					fi
 				fi
 			fi
 		done < <(echo "$dirlist")
@@ -329,4 +376,5 @@ else
 	echo "tree retention" ###
 fi
 
+echo "Done"
 exit 0
