0.1.5
deletions support for folders without subfolders

diff --git a/merge b/merge
--- a/merge
+++ b/merge
@@ -1,7 +1,7 @@
 #!/bin/zsh
 # shellcheck shell=bash
 
-# merge v0.1.4
+# merge v0.1.5
 
 export PATH=/usr/bin:/bin:/usr/sbin:/sbin
 export SYSTEM_VERSION_COMPAT=0
@@ -23,8 +23,15 @@ fi
 deletions=$(grep -v "^$" < "$deleteloc")
 if [[ $deletions ]] ; then
 	rmfiles=true
+	suffixes=$(echo "$deletions" | grep "^\*\." 2>/dev/null)
+	if [[ $suffixes ]] ; then
+		checkext=true
+	else
+		checkext=false
+	fi
 else
 	rmfiles=false
+	checkext=false
 fi
 
 if [[ $1 == "-d" ]] || [[ $1 == "--down" ]] ; then
@@ -42,6 +49,7 @@ if [[ $# -eq 1 ]] ; then
 		exit 1
 	else
 		if ! $mergedown ; then
+			### recursive search for file deletion (see below)
 			echo "Error: single directory file! Nothing to merge!" >&2
 			exit 1
 		else
@@ -55,8 +63,46 @@ if [[ $# -eq 1 ]] ; then
 			targetdir="$filepath"
 			dirlist=$(find "$targetdir" -mindepth 1 -maxdepth 1 -type d 2>/dev/null)
 			if ! [[ $dirlist ]] ; then
-				echo "Error: no subdirectories! Nothing to merge down!" >&2
-				exit 1
+				if $rmfiles ; then
+					quicklist=$(find "$targetdir" -mindepth 1 -maxdepth 1 -type f 2>/dev/null)
+					if [[ $quicklist ]] ; then
+						fdeleted=false
+						while read -r quicklistfile
+						do
+							sourcebase=$(basename "$quicklistfile")
+							if echo "$deletions" | grep -q "^$sourcebase$" &>/dev/null ; then
+								if rm -f "$quicklistfile" &>/dev/null ; then
+									fdeleted=true
+									continue
+								fi
+							fi
+							if $checkext ; then
+								suffix="${sourcebase##*.}"
+								extension=$(echo "$suffix" | tr '[:upper:]' '[:lower:]')
+								if [[ $extension ]] ; then
+									if echo "$suffixes" | grep -q "^\*\.$extension$" &>/dev/null ; then
+										if rm -f "$quicklistfile" &>/dev/null ; then
+											fdeleted=true
+											continue
+										fi
+									fi
+								fi
+							fi
+						done < <(echo "$quicklist")
+						if ! $fdeleted ; then
+							echo "Error: no subdirectories! Nothing to merge down!" >&2
+							exit 1
+						else
+							exit 0
+						fi
+					else
+						echo "Error: no subdirectories! Nothing to merge down!" >&2
+						exit 1
+					fi
+				else
+					echo "Error: no subdirectories! Nothing to merge down!" >&2
+					exit 1
+				fi	
 			fi
 		fi
 	fi
@@ -160,16 +206,6 @@ if $mergedown ; then
 			echo "Error creating target directory!" >&2
 			exit 1
 		fi
-	fi
-	if $rmfiles ; then
-		suffixes=$(echo "$deletions" | grep "^\*\." 2>/dev/null)
-		if [[ $suffixes ]] ; then
-			checkext=true
-		else
-			checkext=false
-		fi
-	else
-		checkext=false
 	fi
 	mverror=false
 	while read -r sourcefile
@@ -293,4 +329,4 @@ else
 	echo "tree retention" ###
 fi
 
-exit
+exit 0
