0.1.7
file protections

diff --git a/merge b/merge
--- a/merge
+++ b/merge
@@ -1,7 +1,7 @@
 #!/bin/zsh
 # shellcheck shell=bash
 
-# merge v0.1.6
+# merge v0.1.7
 
 export PATH=/usr/bin:/bin:/usr/sbin:/sbin
 export SYSTEM_VERSION_COMPAT=0
@@ -43,6 +43,59 @@ else
 	checkext=false
 fi
 
+read -d '' sysparents <<"EOF"
+/etc
+/Library
+/opt
+/opt/local
+/opt/local/etc
+/opt/local/include
+/opt/local/lib
+/opt/local/libexec
+/opt/local/share
+/opt/local/var
+/private
+/private/etc
+/private/tftpboot
+/private/var
+/sbin
+/System
+/System/Library
+/Users
+/usr
+/usr/bin
+/usr/lib
+/usr/libexec
+/usr/local
+/usr/local/Cellar
+/usr/local/etc
+/usr/local/include
+/usr/local/lib
+/usr/local/libexec
+/usr/local/opt
+/usr/local/share
+/usr/local/share/man
+/usr/local/var
+/usr/share
+/usr/share/man
+/usr/standalone
+/var
+/Volumes
+EOF
+# plus: /
+
+read -d '' userparents <<EOF
+$HOMEDIR/.local
+$HOMEDIR/.local/etc
+$HOMEDIR/.local/include
+$HOMEDIR/.local/lib
+$HOMEDIR/.local/share
+$HOMEDIR/.local/share/man
+$HOMEDIR/.local/var
+$HOMEDIR/Library
+EOF
+# plus: $HOMEDIR
+
 if [[ $1 == "-d" ]] || [[ $1 == "--down" ]] ; then
 	mergedown=true
 	shift
@@ -52,8 +105,18 @@ else
 	exit 1 ###
 fi
 
+if ! [[ $* ]] ; then
+	echo "Error: no input" >&2
+	exit 1
+fi
+
 if [[ $# -eq 1 ]] ; then
-	if ! [[ -d $* ]] ; then
+	filepath="$*"
+	if ! [[ -e $* ]] ; then
+		echo "Error: file missing: $filepath" >&2
+		exit 1
+	fi
+	if ! [[ -d "$filepath" ]] ; then
 		echo "Error: no merge of single non-directory files!" >&2
 		exit 1
 	else
@@ -62,7 +125,24 @@ if [[ $# -eq 1 ]] ; then
 			echo "Error: single directory file! Nothing to merge!" >&2
 			exit 1
 		else
-			filepath="$*"
+			parentdir=$(dirname "$filepath")
+			if [[ $parentdir == "$HOMEDIR" ]] ; then
+				echo "Error: protected home file!" >&2
+				exit 1
+			elif [[ $parentdir == "/" ]] ; then
+				echo "Error: protected root file" >&2
+				exit 1
+			else
+				if echo "$userparents" | grep -q "^$parentdir$" &>/dev/null ; then
+					echo "Error: protected user file!" >&2
+					exit 1
+				else
+					if echo "$sysparents" | grep -q "$parentdir$" &>/dev/null ; then
+						echo "Error: protected system file!" >&2
+						exit 1
+					fi
+				fi
+			fi
 			if ! [[ -w "$filepath" ]] ; then
 				echo "Error: directory not writable!" >&2
 				exit 1
@@ -127,6 +207,24 @@ else
 	parentlist=""
 	for filepath in "$@"
 	do
+		parentdir=$(dirname "$filepath")
+		if [[ $parentdir == "$HOMEDIR" ]] ; then
+			echo "Error: protected home file!" >&2
+			exit 1
+		elif [[ $parentdir == "/" ]] ; then
+			echo "Error: protected root file" >&2
+			exit 1
+		else
+			if echo "$userparents" | grep -q "^$parentdir$" &>/dev/null ; then
+				echo "Error: protected user file!" >&2
+				exit 1
+			else
+				if echo "$sysparents" | grep -q "$parentdir$" &>/dev/null ; then
+					echo "Error: protected system file!" >&2
+					exit 1
+				fi
+			fi
+		fi
 		if ! [[ -w "$filepath" ]] ; then
 			echo "Error: at least one file not writable: $filepath" >&2
 			exit 1
